version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  test_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=mvukusic
      - POSTGRES_PASSWORD=mvukusic
      - POSTGRES_DB=test_db
    ports:
      - '5433:5432'
    volumes: 
      - test_db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
  test_db:
    driver: local